# Generated by Django 5.0 on 2024-01-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=80)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('FromEmailAddress', models.EmailField(max_length=50)),
                ('Comments', models.CharField(max_length=500)),
            ],
        ),
    ]
