# Generated by Django 5.0 on 2024-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Comments',
            field=models.CharField(default='Query', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='FromEmailAddress',
            field=models.EmailField(default='Email', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='PhoneNumber',
            field=models.CharField(default='Phone', max_length=15),
        ),
    ]
