# Generated by Django 5.0 on 2024-01-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_alter_contact_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Comments',
            field=models.CharField(max_length=500, verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='FromEmailAddress',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='PhoneNumber',
            field=models.CharField(max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='msg_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Msg_Id'),
        ),
    ]
