# Generated by Django 5.0 on 2024-01-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_alter_contact_comments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Con',
        ),
    ]
