# Generated by Django 5.0 on 2024-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_rename_contact_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='con',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='con',
            name='FromEmailAddress',
        ),
        migrations.RemoveField(
            model_name='con',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='con',
            name='Email',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='con',
            name='Phone',
            field=models.CharField(default=19, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='con',
            name='Query',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
