# Generated by Django 5.0 on 2024-02-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_remove_con_comments_remove_con_fromemailaddress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Con',
            new_name='kon',
        ),
    ]
