# Generated by Django 5.0 on 2024-02-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_rename_kon_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Msg_Id')),
                ('Name', models.CharField(max_length=80)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=50)),
                ('Query', models.CharField(max_length=500)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='con',
        ),
    ]
